# -*- coding: utf-8 -*-
"""3d_openpose.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nI2yVWsJILbT0OKVjm9bpXV9Zz1RiJ5K
"""

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/3d_openpose/Pose_Estimator
!pwd

!python --version

# Commented out IPython magic to ensure Python compatibility.
!wget https://www.python.org/ftp/python/3.6.13/Python-3.6.13.tgz
!tar xvfz Python-3.6.13.tgz
# %cd Python-3.6.13
!./configure
!make
!sudo make install

!python --version

!pip install --upgrade pip
!pip install tensorflow==2.1.0

!pip install opencv-python
!sudo apt-get install build-essential
!pip install tf_slim
!sudo apt install swig
!pip install slidingwindow
!pip install pycocotools
!pip install ipykernel
!pip install pandas
!pip install openpyxl

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/3d_openpose/Pose_Estimator
!pip install -r requirements.txt
# %cd Pose_Estimator/tf_pose/pafprocess
!swig -python -c++ pafprocess.i && python3 setup.py build_ext --inplace

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/3d_openpose/Pose_Estimator
!python run.py --model=mobilenet_thin --resolution=800x400 --image=/content/drive/MyDrive/openpose/